[package]
name = "geotiff"
description = "A GeoTIFF library for Rust"
version = "0.0.2"
edition = "2021"
authors = ["Dominik Bucher <dobucher@ethz.ch>"]
repository = "https://github.com/georust/geotiff"

[dependencies]
delaunator = "1.0"
geo-types = { version = "0.7", features = ["approx", "rstar_0_12"] }
num_enum = "0.7"
num-traits = "0.2"
rstar = "0.12"
tiff = "0.9"

[dev-dependencies]
proj = "0.27"
